version: '3'

services:
  notebook:
    container_name: notebook
    user: root
    privileged: true
    image: psyoblade/data-engineer-notebook:1.1
    restart: always
    depends_on:
      - mysql
      - mongo
    links:
      - mysql
      - mongo
    volumes:
      - ./spark/notebooks:/home/jovyan/work
      - $HOME/.aws/credentials:/home/jovyan/.aws/credentials:ro
      - $HOME/.aws/config:/home/jovyan/.aws/config:ro
    environment:
      - GRANT_SUDO=yes
    ports:
      - "4040:4040"
      - "4041:4041"
      - "8888:8888"
  mysql:
    container_name: mysql
    image: psyoblade/data-engineer-mysql:1.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: sqoop
      MYSQL_PASSWORD: sqoop
    ports:
      - '3306:3306'
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 3s
      timeout: 1s
      retries: 3
    volumes:
      - ./mysql/etc:/etc/mysql/conf.d
  mongo:
    image: mongo:4.4.2
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
networks:
  default:
    name: default_network
